### ISSUE TITLE
Reminder stops working since Reminder Update 0.6.1 Logseq Update 0.9.13 

### ISSUE THREAD

**Issue by acsr** [sethyuan/logseq-plugin-reminder#9]
Does not show up as macOS Notification anymore on MacOS Monterey 12.6.7
Hooks not used for now.
Any hints what log where to watch?

my config is:

```
{
  "remindings": "15m, 5m, 1m",
  "dateTimeFormat": "",
  "disabled": false,
  "alertOffset": 5
}
```

1m was added **after** recognizing the issue and to speedup testing. Same with standard setup.

**Comment by sethyuan** [comment]
Mine is macOS 13.4.1, I just ran a quick test and it worked properly. BTW, `alertOffset` is no longer used, feel free to remove it. Below are the things I think you can try to locate the issue:

1. Did you try to restart Logseq?
2. Are there any error messages in the console?
3. What was changed in your environment? Could it be the Electron upgrade that's causing this? You can try downgrade your Logseq several versions back to confirm.

**Comment by kevin00730** [comment]
I encounter the same problem in logseq 0.9.13 with macOS 13.4.1.
I found when toggling Reminder plugin from off to on, the error below show up.
```
Uncaught (in promise) TypeError: nextDt.getTime is not a function
    at handleReminder (index.d11fd1a1.js:11424:35)
    at async initReminders (index.d11fd1a1.js:11747:9)
    at async Co.main (index.d11fd1a1.js:11680:5)
```
I am not sure if the error is related to that problem.

**Comment by sethyuan** [comment]
@kevin00730 Could be, are you using the newest version of the plugin? Can you post a reminder's text that didn't work?

**Comment by sethyuan** [comment]
@WsinGithub Can you try the newest Logseq v0.9.15? I just ran a quick test on Windows, and it did show the notification.

**Comment by sethyuan** [comment]
All, I have located the problem and released a fix, can you try it?

**Comment by WsinGithub** [comment]
Now I may as well update my Logseq 🐱‍👤.

**Comment by kevin00730** [comment]
v0.6.2 works in logseq 0.9.13 with macOS 13.4.1. 
Thanks.

**Comment by sethyuan** [comment]
Great, then I'm closing. Thank you all!
